[colors]
foreground = "#dcd7ba"
background = "#16161d"
selection_foreground = "#dcd7ba"
selection_background = "#2d2d36"
cursor = "#dcd7ba"
cursor_text_color = "#16161d"
color0 = "#16161d"
color1 = "#c34043"
color2 = "#76946a"
color3 = "#c0a36e"
color4 = "#7e9cd8"
color5 = "#957fb8"
color6 = "#6a9589"
color7 = "#dcd7ba"
color8 = "#444550"
color9 = "#c34043"
color10 = "#76946a"
color11 = "#c0a36e"
color12 = "#7e9cd8"
color13 = "#957fb8"
color14 = "#6a9589"
color15 = "#dcd7ba"
